---
# https://gist.github.com/EntropyWorks/a768b3bc4444146d56be81af05d73fed
# Original idea found at http://stackoverflow.com/a/39083724
#
#   ansible -i inventory.ini add-ssh-keys.yml
#
# 需要安装 sudo yum install -y sshpass
#
- name: Store known hosts of 'all' the hosts in the inventory file
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    ## 修改这里的组. 全部为 all
    ssh_secret_free_groups:
    - mariadb
    - rabbitmq
    - elasticsearch
    ssh_secret_free_hosts: "{{ ssh_secret_free_groups | map('extract', groups) |list | flatten}}"

    ssh_known_hosts: "{{ ssh_secret_free_hosts | map('extract', hostvars, 'ansible_ssh_host') |list}}"

  tasks:
  - name: debug ssh_known_hosts
    debug:
      msg: "{{ ssh_known_hosts }}"

    tags: dbg

  - name: For each host, scan for its ssh public key
    shell: "ssh-keyscan {{ item|default('') }}"
    with_items: "{{ ssh_known_hosts }}"
    register: ssh_known_host_results
    ignore_errors: yes
    tags:
      - ssh

  - name: Remove the public key in the '{{ ssh_known_hosts_file }}'
    known_hosts:
      name: "{{ item.item }}"
      state: "absent"
      path: "{{ ssh_known_hosts_file }}"
    with_items: "{{ ssh_known_host_results.results }}"
    tags:
      - ssh

  - name: Add/update the public key in the '{{ ssh_known_hosts_file }}'
    known_hosts:
      name: "{{ item.item }}"
      key: "{{ item.stdout }}"
      state: "present"
      path: "{{ ssh_known_hosts_file }}"
    with_items: "{{ ssh_known_host_results.results }}"
    tags:
      - ssh

  - name: For each host, ssh-copy-id my ssh public keys to the host
    shell: "sshpass -p '{{ ansible_ssh_pass }}' ssh-copy-id {{ item|default(omit) }}"
    with_items: "{{ groups['all'] | map('extract', hostvars, 'ansible_ssh_host')|list }}"
    when: not (( ansible_ssh_pass is undefined ) or ( ansible_ssh_pass is none ) or ( ansible_ssh_pass | trim == ''))
    tags:
      - sshcopy
